name: Rawhide Build

on:
  workflow_dispatch:
  schedule:
    - cron: '45 5 * * 1'

jobs:
  rawhideBuilds:
    runs-on: ubuntu-latest
    container: 
      image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
    strategy:
      matrix:
        include:
          - os: fedora
            version: rawhide
            dockernamespace: quay.io/fedora/fedora

    steps:
      - uses: actions/checkout@v4

      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=rawhide" >> $GITHUB_ENV
      
      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV
      
      - name: Run CI
        run: ci/${{ matrix.os }}.sh